# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04cd29e04824ddb82d4a5e0aee4c814e87ffdef0ec2b607ad66efc38896a711fc47ecca5bf4f8ddf246358b2484c5261f0b7061a09eaea784358812fe005727d

test:
  secret_key_base: 695a99699031d14d9fb28d451014311e0b97ca89a2b8d08af72e784dd049c4ac745f5228f50b262ed70bb47b3df88c9f3be47014311dad443e67bbf15c5fed27

# Do not keep production secrets in the repository,
# instead read values from the environment.
# NOTE: DO NOT USE THIS FOR PRODUCTION PURPOSES, IT IS INCLUDED IN THIS REPO FOR EASY TESTING
# WHEN DEVELOPING CAPISTRANO GEMS!
production:
  secret_key_base: 6f92bd9393978e4d4979c9c172ec2abc675daa23c57753cbd9f68467f45e6242149fbeedbb98107994ee74943d68ed4f7cedf5e9c2b44d5ec42bbf3db3e39fb5
